easy_t_product_ID:
    path:     /product_id
    defaults: { _controller: APMCoreBundle:Shop/Products:getProductId}

easy_t_product_detail:
    path:     /product_id/{id_prod}
    defaults: { _controller: APMCoreBundle:Shop/Products:ProductDetail}


easy_t_products_cat:
    path:     /product_cat/{id_cat}
    defaults: { _controller: APMCoreBundle:Shop/Products:getProductCat}

easy_t_products_search:
    path:     /search
    defaults: { _controller: APMCoreBundle:Shop/Products:getProductSearch}

easy_t_products_compare:
    path:     /compare
    defaults: { _controller: APMCoreBundle:Shop/Products:getProductCompare}
