easy_t_shopping_home:
    path:     /
    defaults: { _controller: APMCoreBundle:Shop/Shopping:shopping}

easy_t_cart_add:
    path:     /cart/add/{id_pro}
    defaults: { _controller: APMCoreBundle:Shop/Shopping:deleteCart}

easy_t_cart_remove:
    path:     /cart/remove/{id_prod}
    defaults: { _controller:APMCoreBundle:Shop/Shopping:removeCart}

easy_t_cart_update:
    path:     /cart/update
    defaults: { _controller:APMCoreBundle:Shop/Shopping:updateCart}

