if(typeof Object.create!=='function'){Object.create=function(obj){function F(){}
F.prototype=obj;return new F();};}
(function($,window,document,undefined){var tmAdvancedFilterObj={init:function(){self=this;$(document).on('change','.tmadvancedfilter select',function(){self.refreshFilter($(this));});$(document).on('change','.tmadvancedfilter input[type="radio"]',function(){self.refreshFilter($(this));});$(document).on('change','.tmadvancedfilter input[type="checkbox"]',function(){self.refreshFilter($(this));});$(document).on('change','.tmadvancedfilter input[data-type="price"]',function(){self.refreshFilter($(this));});$(document).on('click','#filter-selected-parameters li',function(){self.disableParameter($(this));});$(document).on('click','#adv-filter',function(){self.advSearch();});self.refreshUniformScript();},refreshFilter:function(elem){var elements=elem.parents('.tmadvancedfilter').find('select, input');var container=elem.parents('.tmadvancedfilter');var form=elem.parents('form');var params={};params['action']='refreshFilter';container.append('<div class="loading"></div>');elements.each(function(){if($(this).attr('type')=='radio'||$(this).attr('type')=='checkbox'){if($(this).attr('checked')){if(params[$(this).attr('name')]){var values=self.getValuesArray(container,$(this).attr('name'));params[$(this).attr('name')]=values;}else{params[$(this).attr('name')]=$(this).val();}}}else if($(this).attr('data-type')&&$(this).attr('data-type')=='price'){var prices=self.getPriceRange(container,$(this).attr('name'));params[$(this).attr('name')]=prices;}else{params[$(this).attr('name')]=$(this).val();}});$.ajax({type:'POST',url:baseDir+'modules/tmadvancedfilter/tmadvancedfilter-ajax.php',headers:{"cache-control":"no-cache"},dataType:'json',data:params,success:function(response){if(response.status){var isActive=$('#top-filter').find('.filter-body').hasClass('active');container.parents('form').html(response.message);if(isActive){$('#top-filter').find('.filter-body').addClass('active');}
if(response.status){self.refreshHash(response.url);}
if(response.products){form.find('button[name="submit'+response.type+'TmAdvancedFilter"] .count').html(response.count);}else{form.find('button[name="submit'+response.type+'TmAdvancedFilter"] .count').html('0');}
self.refreshUniformScript();}else{}
container.find('.loading').remove();}})},getValuesArray:function(container,name){var elements=container.find('input[name="'+ name+'"]:checked');var result='';elements.each(function(index){if(index>0){result+='|'+ $(this).val();}else{result+=$(this).val();}});return result;},getPriceRange:function(container,name){var type=container.find('select[data-type="price"], input[data-type="price"]').attr('data-element-type');var from=container.find(type+'[data-type="price"][data-type-value="from"]').val();var to=container.find(type+'[data-type="price"][data-type-value="to"]').val();if(from==0&&to==0){return;}
if(!from){from=0;}
if(!to){to=0;}
return from+'|'+ to;},refreshHash:function(newhash){if($('body').attr('id')=='module-tmadvancedfilter-filter'){history.pushState({},null,newhash);}},refreshUniformScript:function(){if(typeof bindUniform!=='undefined'){bindUniform();}},disableParameter:function(parameter){var form=parameter.parents('form');var field_type=parameter.attr('data-filter-field-type');var field_parameter=parameter.attr('data-filter-field');var id_parameter=parameter.attr('data-filter-field-id');switch(field_type){case'checkbox':if(!id_parameter){form.find('input[name="'+ field_parameter+'[]"]').trigger('click');}else{form.find('input[name="'+ field_parameter+'[]"][value="'+ id_parameter+'"]').trigger('click');}
break;case'radio':if(!id_parameter){form.find('input[name="'+ field_parameter+'"]').attr('checked',false).trigger('change');}else{form.find('input[name="'+ field_parameter+'"][value="'+ id_parameter+'"]').attr('checked',false).trigger('change');}
break;case'select':form.find('select[name="'+ field_parameter+'"] option:selected').attr('selected',false).trigger('change');break;case'range-select':var price_field=false;form.find('select[name="'+ field_parameter+'[]"] option:selected').each(function(){if(!price_field){price_field=$(this);}
$(this).attr('selected',false);});price_field.trigger('change');break;case'range-input':form.find('input[name="'+ field_parameter+'[]"]').each(function(){$(this).val('');});form.find('input[name="'+ field_parameter+'[]"][data-type-value="from"]').trigger('change');break;}},advSearch:function(){var adv_content=$('#top-filter').find('.filter-content');adv_content.slideToggle();$('#top-filter').find('.filter-body').toggleClass('active');}};$.fn.tmAdvancedFilter=function(){return this.each(function(){var filter=Object.create(tmAdvancedFilterObj);filter.init(this);$.data(this,'tmAdvancedFilter',filter);});};})(jQuery,window,document);$(document).ready(function(){$('.tmadvancedfilter').tmAdvancedFilter();});