#--------------------------- Objects factory ------------------------------------------
apm_vente_boutique_index:
    path:     /
    defaults: { _controller: "APMVenteBundle:Boutique:index" }
    methods:  [GET, POST]

apm_vente_boutique_index_utilisateur:
    path:     /{id}
    defaults: { _controller: "APMVenteBundle:Boutique:index" }
    methods:  [GET, POST]

apm_vente_boutique_show:
    path:     /{id}/show
    defaults: { _controller: "APMVenteBundle:Boutique:show" }
    methods:  GET

apm_vente_boutique_show-image:
    path:     /{id}/show-image
    defaults: { _controller: "APMVenteBundle:Boutique:showImage" }
    methods:  [GET, POST]

apm_vente_boutique_new:
    path:     /new
    defaults: { _controller: "APMVenteBundle:Boutique:new" }
    methods:  [GET, POST]

apm_vente_boutique_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMVenteBundle:Boutique:edit" }
    methods:  [GET, POST]

apm_vente_boutique_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMVenteBundle:Boutique:delete" }
    methods:  DELETE

apm_vente_boutique_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMVenteBundle:Boutique:deleteFromList" }

apm_vente_AjaxBoutique_index:
    path:     /query/ajax-boutique
    defaults: { _controller: "APMVenteBundle:AjaxQueryVente:indexBoutique" }
    methods:  GET

#------------------- Shop publique ---------------------------------------------