#--------------------------- Objects factory ------------------------------------------
apm_vente_boutique_index:
    path:     /
    defaults: { _controller: "APMVenteBundle:Boutique:index" }
    methods:  GET

apm_vente_boutique_show:
    path:     /{id}/show
    defaults: { _controller: "APMVenteBundle:Boutique:show" }
    methods:  GET

apm_vente_boutique_new:
    path:     /new
    defaults: { _controller: "APMVenteBundle:Boutique:new" }
    methods:  [GET, POST]

apm_vente_boutique_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMVenteBundle:Boutique:edit" }
    methods:  [GET, POST]

apm_vente_boutique_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMVenteBundle:Boutique:delete" }
    methods:  DELETE

apm_vente_boutique_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMVenteBundle:Boutique:deleteFromList" }

#----------------------------- Handle offers --------------------------------------
#------Insertion/desinsertion----
apm_vente_boutique_inserer_offre:
    path:     /{id}/inserer-offre/{boutique_id}
    defaults: { _controller: "APMVenteBundle:Trade:insererOffreDansBoutique" }
#    methods:  [GET]
apm_vente_boutique_desinserer_offre:
    path:     /{id}/desinserer-offre/{boutique_id}
    defaults: { _controller: "APMVenteBundle:Trade:desinsererOffreDansBoutique" }
    #methods:  POST
#-----
apm_vente_boutique_inserer_categorie:
    path:     /{id}/inserer-categorie/{boutique_id}
    defaults: { _controller: "APMVenteBundle:Trade:insererCategorieDansBoutique" }
#    methods:  [GET]
apm_vente_boutique_desinserer_categorie:
    path:     /{id}/desinserer-categorie/{boutique_id}
    defaults: { _controller: "APMVenteBundle:Trade:desinsererCategorieDansBoutique" }
#    methods:  [GET]
#-------Publication/depublication----
apm_vente_boutique_publier:
    path:     /{id}/publier-boutique
    defaults: { _controller: "APMVenteBundle:Trade:publierBoutique" }
#    methods:  [GET]
apm_vente_boutique_depublier:
    path:     /{id}/depublier-boutique
    defaults: { _controller: "APMVenteBundle:Trade:depublierBoutique" }
#   methods:  [GET]
#-------------------------- Handle Boutique ---------------------------------------------------
apm_vente_boutique_transferer:
    path:     /{id}/transferer-boutique/{source_id}/{destinataire_id}/{ordre_id}/{livraison_id}
    defaults: { _controller: "APMVenteBundle:Trade:transfererBoutique" }

