apm_vente_offre_index:
    path:     /index
    defaults: { _controller: "APMVenteBundle:Offre:index" }

apm_vente_offre_loader:
    path:     /ajax-table_1
    defaults: { _controller: "APMVenteBundle:Offre:loadTable" }

apm_vente_offre_delete:
    path:     /delete
    defaults: { _controller: "APMVenteBundle:Offre:delete" }

#---------------------------- old routes -----------------------
apm_vente_offre_boutique-categorie_index:
    path:     /boutique/{id}/categorie/{categorie_id}
    defaults: { _controller: "APMVenteBundle:Offre:index" }
    methods:  [GET,POST]

apm_vente_offre_boutique_index:
    path:     /boutique/{id}
    defaults: { _controller: "APMVenteBundle:Offre:index" }
    methods:  [GET,POST]

apm_vente_offre_show-image:
    path:     /{id}/show-image
    defaults: { _controller: "APMVenteBundle:Offre:showImage" }
    methods:  [GET, POST]

apm_vente_AjaxOffre_index:
    path:     /query/ajax-offre
    defaults: { _controller: "APMVenteBundle:AjaxQueryVente:indexOffre"}
    methods:  GET