
#---------------------------- routes -----------------------
apm_vente_offre_index:
    path:     /
    defaults: { _controller: "APMVenteBundle:Offre:index" }
    methods:  [GET,POST]

apm_vente_offre_boutique-categorie_index:
    path:     /boutique/{id}/categorie/{categorie_id}
    defaults: { _controller: "APMVenteBundle:Offre:index" }
    methods:  [GET,POST]

apm_vente_offre_boutique_index:
    path:     /boutique/{id}
    defaults: { _controller: "APMVenteBundle:Offre:index" }
    methods:  [GET,POST]

apm_vente_offre_boutique_index:
    path:     /user/{id}
    defaults: { _controller: "APMVenteBundle:Offre:index" }
    methods:  [GET,POST]

apm_vente_offre_show:
    path:     /{id}/show
    defaults: { _controller: "APMVenteBundle:Offre:show" }
    methods:  GET

apm_vente_offre_show-image:
    path:     /{id}/show-image
    defaults: { _controller: "APMVenteBundle:Offre:showImage" }
    methods:  [GET, POST]

apm_vente_offre_new:
    path:     /new
    defaults: { _controller: "APMVenteBundle:Offre:new" }
    methods:  [GET, POST]

apm_vente_offre_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMVenteBundle:Offre:edit" }
    methods:  [GET, POST]

apm_vente_offre_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMVenteBundle:Offre:delete" }
    methods:  DELETE

apm_vente_offre_delete_ajax:
    path:     /delete-ajax
    defaults: { _controller: "APMVenteBundle:Offre:delete" }
    methods: POST

apm_vente_offre_groupe_index:
    path:     /{groupe_id}/offres
    defaults: { _controller: "APMVenteBundle:Offre:index" }
    methods:  [GET, POST]

apm_vente_offre_show-image_ajax:
    path:     /image
    defaults: { _controller: "APMVenteBundle:Offre:ImageLoader" }