apm_vente_rabais_offre_index:
    path:     /{id}
    defaults: { _controller: "APMVenteBundle:Rabais_offre:index" }
    methods:  GET

apm_vente_rabais_user_index:
    path:     /utilisateur
    defaults: { _controller: "APMVenteBundle:Rabais_offre:index" }
    methods:  GET

apm_vente_rabais_offre_show:
    path:     /{id}/show
    defaults: { _controller: "APMVenteBundle:Rabais_offre:show" }
    methods:  GET

apm_vente_rabais_offre_new:
    path:     /new/{id}
    defaults: { _controller: "APMVenteBundle:Rabais_offre:new" }
    methods:  [GET, POST]

apm_vente_rabais_offre_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMVenteBundle:Rabais_offre:edit" }
    methods:  [GET, POST]

apm_vente_rabais_offre_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMVenteBundle:Rabais_offre:delete" }
    methods:  DELETE

apm_vente_rabais_offre_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMVenteBundle:Rabais_offre:deleteFromList" }

