apm_vente_remise_index:
    path:     /{id}
    defaults: { _controller: "APMVenteBundle:Remise:index" }
    methods:  GET

apm_vente_remise_show:
    path:     /{id}/show
    defaults: { _controller: "APMVenteBundle:Remise:show" }
    methods:  GET

apm_vente_remise_new:
    path:     /new/{id}
    defaults: { _controller: "APMVenteBundle:Remise:new" }
    methods:  [GET, POST]

apm_vente_remise_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMVenteBundle:Remise:edit" }
    methods:  [GET, POST]

apm_vente_remise_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMVenteBundle:Remise:delete" }
    methods:  DELETE

apm_vente_remise_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMVenteBundle:Remise:deleteFromList" }


