apm_vente_suggestion_offre_index:
    path:     /
    defaults: { _controller: "APMVenteBundle:Suggestion_produit:index" }
    methods:  GET

apm_vente_suggestion_offre_show:
    path:     /{id}/show
    defaults: { _controller: "APMVenteBundle:Suggestion_produit:show" }
    methods:  GET

apm_vente_suggestion_offre_new:
    path:     /new
    defaults: { _controller: "APMVenteBundle:Suggestion_produit:new" }
    methods:  [GET, POST]

apm_vente_suggestion_offre_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMVenteBundle:Suggestion_produit:edit" }
    methods:  [GET, POST]

apm_vente_suggestion_offre_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMVenteBundle:Suggestion_produit:delete" }

apm_vente_suggestion_offre_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMVenteBundle:Suggestion_produit:deleteFromList" }
