apm_vente_transaction_produit_user_index:
    path:     /
    defaults: { _controller: "APMVenteBundle:Transaction_produit:index" }
    methods:  GET

apm_vente_transaction_produit_offre_index:
    path:     /offre/{offre_id}
    defaults: { _controller: "APMVenteBundle:Transaction_produit:index" }
    methods:  GET

apm_vente_transaction_produit_boutique_index:
    path:     /boutique/{id}
    defaults: { _controller: "APMVenteBundle:Transaction_produit:index" }
    methods:  GET

apm_vente_transaction_produit_liste_index:
    path:     /liste/offres-transaction/{id}
    defaults: { _controller: "APMVenteBundle:Transaction_produit:listeOffres" }
    methods:  GET

apm_vente_transaction_produit_show:
    path:     /{id}/show
    defaults: { _controller: "APMVenteBundle:Transaction_produit:show" }
    methods:  GET

apm_vente_transaction_produit_new:
    path:     /transaction-produit/new/{id}
    defaults: { _controller: "APMVenteBundle:Transaction_produit:new" }
    methods:  [GET, POST]

apm_vente_transaction_produit_accueil_new:
    path:     /transaction-offre/new
    defaults: { _controller: "APMVenteBundle:Transaction_produit:new" }
    methods:  [GET, POST]

apm_vente_transaction_produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMVenteBundle:Transaction_produit:edit" }
    methods:  [GET, POST]

apm_vente_transaction_produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMVenteBundle:Transaction_produit:delete" }
    methods:  DELETE

apm_vente_transaction_produit_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMVenteBundle:Transaction_produit:deleteFromList" }


