apm_vente_transaction_produit_index:
    path:     /{id}/transaction
    defaults: { _controller: "APMVenteBundle:Transaction_produit:index" }
    methods:  [GET, POST]

apm_vente_transaction_produit_show:
    path:     /{id}/show
    defaults: { _controller: "APMVenteBundle:Transaction_produit:show" }
    methods:  GET

apm_vente_transaction_produit-transaction_new:
    path:     /transaction/{id}/new
    defaults: { _controller: "APMVenteBundle:Transaction_produit:new" }
    methods:  [GET, POST]

apm_vente_transaction_produit_new:
    path:     /transaction-produit/new
    defaults: { _controller: "APMVenteBundle:Transaction_produit:new" }
    methods:  [GET, POST]

apm_vente_transaction_produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMVenteBundle:Transaction_produit:edit" }
    methods:  [GET, POST]

apm_vente_transaction_produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMVenteBundle:Transaction_produit:delete" }
    methods:  DELETE

apm_vente_transaction_produit_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMVenteBundle:Transaction_produit:deleteFromList" }

