<?php

namespace APM\MarketingReseauBundle\Repository;

/**
 * Reseau_conseillersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Reseau_conseillersRepository extends \Doctrine\ORM\EntityRepository
{
}
