apm_marketing_distribue_commissionnement:
    resource: "@APMMarketingDistribueBundle/Resources/config/routing/commissionnement.yml"
    prefix:   /marketing_commissionnement

apm_marketing_distribue_conseiller:
    resource: "@APMMarketingDistribueBundle/Resources/config/routing/conseiller.yml"
    prefix:   /marketing_conseiller

apm_marketing_distribue_quota:
    resource: "@APMMarketingDistribueBundle/Resources/config/routing/quota.yml"
    prefix:   /marketing_quota

apm_marketing_distribue_homepage:
    path:     /marketing
    defaults: { _controller: APMMarketingDistribueBundle:Default:index }

apm_marketing_distribue_conseiller_boutique:
    resource: "@APMMarketingDistribueBundle/Resources/config/routing/conseiller_boutique.yml"
    prefix:   /marketing_conseiller_boutique