apm_marketing_commissionnement:
    type: rest
    resource: APM\MarketingDistribueBundle\Controller\CommissionnementController
    name_prefix: api_marketing_

apm_marketing_conseiller:
    type: rest
    resource: APM\MarketingDistribueBundle\Controller\ConseillerController
    name_prefix: api_marketing_

apm_marketing_quota:
    type: rest
    resource: APM\MarketingDistribueBundle\Controller\QuotaController
    name_prefix: api_marketing_

apm_marketing_conseiller_boutique:
    type: rest
    resource: APM\MarketingDistribueBundle\Controller\Conseiller_boutiqueController
    name_prefix:   api_marketing_