apm_achat_groupe:
    resource: "@APMAchatBundle/Resources/config/routing/groupe_offre.yml"
    prefix:   /achat_groupe_offre

apm_achat_service_apres_vente:
    resource: "@APMAchatBundle/Resources/config/routing/service_apres_vente.yml"
    prefix:   /achat_service_apres_vente

apm_achat_specification_achat:
    resource: "@APMAchatBundle/Resources/config/routing/specification_achat.yml"
    prefix:   /achat_specification

apm_achat_homepage:
    path:     /achat
    defaults: { _controller: "APMAchatBundle:Default:index" }
