apm_achat_groupe:
    type: rest
    resource: APM\AchatBundle\Controller\Groupe_offreController
    name_prefix:   api_achat_

apm_achat_service_apres_vente:
    type: rest
    resource: APM\AchatBundle\Controller\Service_apres_venteController
    name_prefix:  api_achat_

apm_achat_specification_achat:
    type: rest
    resource: APM\AchatBundle\Controller\Specification_achatController
    name_prefix:  api_achat_