
#--------------------- pages utilisateur ----------------------------------------------
apm_core_user_dashboard:
    type: rest
    resource: APM\CoreBundle\Controller\UserDashboardController
    name_prefix:   api_core_

apm_core_user_platform:
    type: rest
    resource: APM\CoreBundle\Controller\MainSiteController
    name_prefix:   api_core_

apm_core_user-dashboard_ajax-notification:
    type: rest
    resource: APM\CoreBundle\Controller\AjaxNotificationController
    name_prefix:  api_core_

#---------------------------------------- gérer les Fonctionnalités du systeme------------------------------------------------
apm_core_fonction_offre:
    type: rest
    resource: APM\CoreBundle\Controller\TradeController
    name_prefix:   api_core_