apm_analyse_et_traitement:
    resource: "@APMAnalyseEtTraitementBundle/Resources/config/routing.yml"
    prefix:   /apm

apm_controle_et_securite:
    resource: "@APMControleEtSecuriteBundle/Resources/config/routing.yml"
    prefix:   /apm

apm_animation:
    resource: "@APMAnimationBundle/Resources/config/routing.yml"
    prefix:   /apm

apm_utilisateur:
    resource: "@APMUserBundle/Resources/config/routing.yml"
    prefix:   /apm

apm_admin:
    resource: "@APMAdminBundle/Resources/config/routing.yml"
    prefix:   /apm

apm_marketing_reseau:
    resource: "@APMMarketingReseauBundle/Resources/config/routing.yml"
    prefix:   /apm

apm_marketing_dristribue:
    resource: "@APMMarketingDistribueBundle/Resources/config/routing.yml"
    prefix:   /apm

apm_transport:
    resource: "@APMTransportBundle/Resources/config/routing.yml"
    prefix:   /apm

apm_vente:
    resource: "@APMVenteBundle/Resources/config/routing.yml"
    prefix:   /apm

apm_achat:
    resource: "@APMAchatBundle/Resources/config/routing.yml"
    prefix:   /apm

apm_core:
    resource: "@APMCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"