app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"

#fos_comment_api:
 #   type: rest
  #  resource: "@FOSCommentBundle/Resources/config/routing.yml"
   # prefix: /api
    #defaults: { _format: html }


routing_rest:
    resource: "routing_rest.yml"
    prefix:   /apm

#api_login_check:
#    path: /login_check
#----------
apm_security_login:
    type:  rest
    resource: APM\UserBundle\Controller\SecurityController

apm_user_resetting:
    type:  rest
    resource: APM\UserBundle\Controller\ResettingController
    prefix: /reset-password

apm_user_registration:
    type:  rest
    resource: APM\UserBundle\Controller\RegistrationUtilisateurAVMController
    prefix: /user

apm_staff_registration:
    type:  rest
    resource: APM\UserBundle\Controller\RegistrationAdminController
    prefix: /staff
