
#-------------------------------------------- api routes -----------------------------------------
routing_rest:
    resource: "routing_rest.yml"
    prefix:   /apm

#-------------------------------------------- third party routes ---------------------------------
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/api/doc"

nelmio_api_swagger:
    resource: "@NelmioApiDocBundle/Resources/config/swagger_routing.yml"
    prefix: /api/docs/swagger

fos_user_registration_check_email:
    path:     /check-email-mask
    #defaults: { _controller: "APMUserBundle:Registration:checkEmailAction" }
    #methods:  GET
#------------------------------- user account ----------------------------------------------------
apm_security_login:
    type:  rest
    resource: APM\UserBundle\Controller\SecurityController

apm_user_resetting:
    type:  rest
    resource: APM\UserBundle\Controller\ResettingController
    prefix: /reset-password

apm_user_registration_user:
    type:  rest
    resource: APM\UserBundle\Controller\RegistrationUserController
    prefix: /user

apm_user_registration_staff:
    type:  rest
    resource: APM\UserBundle\Controller\RegistrationStaffController
    prefix: /staff



#---------------------------- staff management ability ----------------------------------------
apm_core_staff_analyste:
    resource: "@APMAdminBundle/Resources/config/staff/analyste.yml"
    prefix:   /staff/analyste

apm_core_staff_auditeur:
    resource: "@APMAdminBundle/Resources/config/staff/auditeur.yml"
    prefix:   /staff/auditeur

apm_core_staff_explorateur:
    resource: "@APMAdminBundle/Resources/config/staff/explorateur.yml"
    prefix:   /staff/explorateur

apm_core_staff_comptable:
    resource: "@APMAdminBundle/Resources/config/staff/comptable.yml"
    prefix:   /staff/comptable

apm_core_staff_super-admin:
    resource: "@APMAdminBundle/Resources/config/staff/super-admin.yml"
    prefix:   /staff/superAdmin