# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
    #--------------------------------------------
        ROLE_STAFF: ROLE_USER
    #---Rôle du staff spécialisés---------------
        ROLE_AUDIT:   ROLE_STAFF #Controlleurs
        ROLE_ANALYSE: ROLE_STAFF #Analystes
        ROLE_EXP:     ROLE_STAFF #Exploitation
        ROLE_COMP:    ROLE_STAFF #Comptable
        ROLE_ADMIN:   [ROLE_AUDIT,ROLE_ANALYSE,ROLE_EXP,ROLE_COMP] #sous admin

    #--------------------------------------------
    #---Rôle du  super administrateur
        ROLE_GESTIONNAIRE: ROLE_STAFF # manage staff registration
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_GESTIONNAIRE]
    #--------------------------------------------
    #---Rôle des utilisateurs avm
        ROLE_USERAVM:       ROLE_USER
        ROLE_BOUTIQUE:      ROLE_USERAVM
        ROLE_TRANSPORTEUR:  ROLE_USERAVM
        ROLE_CONSEILLER:    ROLE_USERAVM
        ROLE_CONSEILLER_A2: ROLE_CONSEILLER
    #-------------------------------------------
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        healthcheck:
            pattern: ^/ping$
            anonymous: true


        api_user_register:
            pattern: ^/user/register
            anonymous: true


        api_staff_register:
            pattern: ^/staff/register
            anonymous: true


        api_docs:
            pattern: ^/doc
            anonymous: true


        api_password_reset:
            pattern: ^/reset-password
            anonymous: true


        api_login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login
                require_previous_session: false
                use_forward: true
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure


        main:
            pattern: ^/
            stateless: true
            #lexik_jwt: ~
            logout:
                path:                 /logout
                target:               /test
                invalidate_session:   true
                #success_handler:      ~
            guard:
                 authenticators:
                     - lexik_jwt_authentication.jwt_token_authenticator
            #provider: fos_userbundle # optional
            #anonymous: ~


    access_control:

    #     pages accessibles aux utilisateurs anonymes
        - { path: ^/ping, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY } # This is for All users logged in or anonymous
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/apm/core/anonymous, role: IS_AUTHENTICATED_ANONYMOUSLY}

        - { path: ^/change-password, role: IS_AUTHENTICATED_FULLY } # This is strictly for users who have successfully logged in and not via remembered me cookie
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }


        - { path: ^/staff/register, role: ROLE_GESTIONNAIRE}
    #     pages accessibles aux utilisateurs avm authentifiés
        - { path: ^/apm/core/user, role: ROLE_USERAVM }
    #     pages accessibles aux Gérants Boutiques et aux propriétaires
        - { path: ^/apm/core/gerant-boutique, role: ROLE_BOUTIQUE }
    #     pages accessibles aux Transporteurs
        - { path: ^/apm/core/transport, role: ROLE_TRANSPORTEUR }
    #     pages accessibles aux Conseillers des Réseaux
        - { path: ^/apm/core/conseiller, role: ROLE_CONSEILLER }
    #     pages accessibles aux administrateurs
          #  pages accessibles aux administrateurs spécialisés
                #  ex: controleurs, analystes, comptables etc.
                  #  pages accessibles aux controleurs
        - { path: ^/apm/core/staff/auditeur, role: ROLE_AUDIT}
                  #  pages accessibles aux analystes
        - { path: ^/apm/core/staff/analyste, role: ROLE_ANALYSE}
                  #  pages accessibles aux comptables
        - { path: ^/apm/core/staff/comptable, role: ROLE_COMP}
                  #  pages accessibles au service d'exploitation
        - { path: ^/apm/core/staff/explorateur, role: ROLE_EXP}
                  #  pages accessibles aux administrateurs
        - { path: ^/apm/core/gestionnaire, role: ROLE_ADMIN} #gestion du business
          #   pages accessibles au super admin

        - { path: ^/, role: ROLE_SUPER_ADMIN} # Everything that has not been included in any careful path belong to the super user






