# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
    #--------------------------------------------
    #---Rôle du staff spécialisés---------------
        ROLE_AUDIT:   ROLE_USER #Controlleurs
        ROLE_ANALYSE: ROLE_USER #Analystes
        ROLE_EXP:     ROLE_USER #Exploitation
        ROLE_COMP:    ROLE_USER #Comptable
        ROLE_ADMIN:   [ROLE_AUDIT,ROLE_ANALYSE,ROLE_EXP,ROLE_COMP] #sous admin

    #--------------------------------------------
    #---Rôle du  super administrateur
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    #--------------------------------------------
    #---Rôle des utilisateurs avm
        ROLE_USERAVM:       ROLE_USER
        ROLE_BOUTIQUE:      ROLE_USERAVM
        ROLE_TRANSPORTEUR:  ROLE_USERAVM
        ROLE_CONSEILLER:    ROLE_USERAVM
        ROLE_CONSEILLER_A2: ROLE_CONSEILLER
    #-------------------------------------------
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            #remember_me:
                #secret:   '%secret%'
                #lifetime: 100 # in seconds
                #path:     /

                        # by default, the feature is enabled by checking a
                        # checkbox in the login form (see below), uncomment the
                        # following line to always enable it.
                #always_remember_me: true
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # login success redirecting options (read further below)
                always_use_default_target_path: false
                default_target_path:            /easy-trade/user/dashboard
                target_path_parameter:          _target_path
                use_referer:                    false
            logout:       true
            anonymous:    true
            http_basic: ~


    access_control:

    #     pages accessibles aux utilisateurs anonymes
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY } # This is for All users logged in or anonymous
        - { path: ^/relogin, role: IS_AUTHENTICATED_ANONYMOUSLY } # This is for All users logged in or anonymous
        - { path: ^/logout, role: IS_AUTHENTICATED_REMEMBERED }  # This is for users logged in even with a remembered me cokie
        - { path: ^/change-password, role: IS_AUTHENTICATED_FULLY } # This is strictly for users who have successfully logged in and not via remembered me cookie
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/lock-dashboard, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/register/utilisateur-avm, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/easy-trade/costumer, role: IS_AUTHENTICATED_ANONYMOUSLY}

    #     pages accessibles aux utilisateurs avm authentifiés
        - { path: ^/easy-trade/user, role: ROLE_USERAVM }
    #     pages accessibles aux Gérants Boutiques et aux propriétaires
        - { path: ^/easy-trade/gerant-boutique, role: ROLE_BOUTIQUE }
    #     pages accessibles aux Transporteurs
        - { path: ^/easy-trade/transport, role: ROLE_TRANSPORTEUR }
    #     pages accessibles aux Conseillers des Réseaux
        - { path: ^/easy-trade/conseiller, role: ROLE_CONSEILLER }
    #     pages accessibles aux administrateurs
          #  pages accessibles aux administrateurs spécialisés
                #  ex: controleurs, analystes, comptables etc.
                  #  pages accessibles aux controleurs
        - { path: ^/easy-trade/staff/auditeur, role: ROLE_AUDIT}
                  #  pages accessibles aux analystes
        - { path: ^/easy-trade/staff/analyste, role: ROLE_ANALYSE}
                  #  pages accessibles aux comptables
        - { path: ^/easy-trade/staff/comptable, role: ROLE_COMP}
                  #  pages accessibles au service d'exploitation
        - { path: ^/easy-trade/staff/explorateur, role: ROLE_EXP}
                  #  pages accessibles aux administrateurs
        - { path: ^/apm/gestionnaire, role: ROLE_ADMIN} #gestion du business
          #   pages accessibles au super admin
#        - { path: ^/register-admin, role: ROLE_SUPER_ADMIN }

        - { path: ^/apm, role: ROLE_USERAVM }
        #Preventing from any access
        - { path: /apm, role: ROLE_SUPER_ADMIN } # Everything that is below or above this path belong to the super user

        - { path: /easy-trade, role: ROLE_SUPER_ADMIN}
        - { path: ^/, role: ROLE_SUPER_ADMIN} # Everything that has not been included in any careful path belong to the super user






