# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

#parameters:
#    parameter_name: value

services:
 #   app.form.registration:
  #      class: APMUserBundle\Form\RegistrationType
   #     tags:
     #       - { name: form.type, alias: lgp_user_registration }

