apm_vente_boutique:
    resource: "@APMVenteBundle/Resources/config/routing/boutique.yml"
    prefix:   /vente/boutique

apm_vente_homepage:
    path:     /vente
    defaults: { _controller: APMVenteBundle:Default:index }

apm_vente_categorie:
    resource: "@APMVenteBundle/Resources/config/routing/categorie.yml"
    prefix:   /vente/categorie

apm_vente_offre:
    resource: "@APMVenteBundle/Resources/config/routing/offre.yml"
    prefix:   /vente/offre

apm_vente_rabais_offre:
    resource: "@APMVenteBundle/Resources/config/routing/rabais_offre.yml"
    prefix:   /vente/rabais_offre

apm_vente_remise:
    resource: "@APMVenteBundle/Resources/config/routing/remise.yml"
    prefix:   /vente/remise

apm_vente_transaction_produit:
    resource: "@APMVenteBundle/Resources/config/routing/transaction_produit.yml"
    prefix:   /vente/transaction_produit

apm_vente_transaction:
    resource: "@APMVenteBundle/Resources/config/routing/transaction.yml"
    prefix:   /vente/transaction