apm_vente_boutique:
    type: rest
    resource: APM\VenteBundle\Controller\BoutiqueController
    name_prefix: api_vente_

apm_vente_categorie:
    type: rest
    resource: APM\VenteBundle\Controller\CategorieController
    name_prefix: api_vente_

apm_vente_offre:
    type: rest
    resource: APM\VenteBundle\Controller\OffreController
    name_prefix: api_vente_

apm_vente_rabais_offre:
    type: rest
    resource: APM\VenteBundle\Controller\Rabais_offreController
    name_prefix: api_vente_

apm_vente_remise:
    type: rest
    resource: APM\VenteBundle\Controller\RemiseController
    name_prefix: api_vente_

apm_vente_transaction_produit:
    type: rest
    resource: APM\VenteBundle\Controller\Transaction_produitController
    name_prefix: api_vente_

apm_vente_transaction:
    type: rest
    resource: APM\VenteBundle\Controller\TransactionController
    name_prefix: api_vente_

    #resource="@FOSUserBundle/Resources/config/routing/security.xml"