apm_marketing_reseau_conseiller_index:
    path:     /conseiller/{id}
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:index" }
    methods:  GET

apm_marketing_reseau_index:
    path:     /conseiller
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:index" }
    methods:  GET

apm_marketing_reseau_new:
    path:     /new
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:new" }
    methods:  PUT

apm_marketing_reseau_add:
    path:     /member-add/{id}
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:handleNetworkingMembers" }
    methods:  [GET, POST]

apm_marketing_reseau_promote:
    path:     /member-promote/{id}
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:promoteMember" }
    methods:  [GET, POST]