apm_marketing_reseau_conseiller_index:
    path:     /conseiller/{id}
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:index" }
    methods:  GET

apm_marketing_reseau_index:
    path:     /conseiller
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:index" }
    methods:  GET

apm_marketing_reseau_new:
    path:     /new
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:new" }
    methods:  PUT

apm_marketing_reseau_add:
    path:     /member-add/{id}
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:addMember" }

#apm_marketing_reseau_right_add:
 #   path:     /right-add/{id}
  #  defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:addRightMember" }


apm_marketing_reseau_left_promote:
    path:     /left-promote/{id}
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:promoteLeftMember" }

apm_marketing_reseau_right_promote:
    path:     /right-promote/{id}
    defaults: { _controller: "APMMarketingReseauBundle:Reseau_conseillers:promoteRightMember" }
