
#---------------------- Handle offre on Trade-------------------------------------------------
#--------- accès exclusif: Permet d'admettre ou de revoquer la visibilité d'un objet à un utilisateur donné ---------
apm_vente_offre_restreindre:
    path:     /{id}/admettre-utilisateur/{user_id}
    defaults: { _controller: "APMVenteBundle:Trade:restreindreOffreAUtilisateur" }
apm_vente_offre_exclure:
    path:     /{id}/exclure-utilisateur/{user_id}
    defaults: { _controller: "APMVenteBundle:Trade:exclureOffreAUtilisateur" }
#--------- transferer offre--------------------------
# Lien cliqué après avoir rempli le formulaire de transfert >>soumettre
apm_vente_offre_transferer:
    path:     /{id}/transferer-offre/{source_id}/{destinataire_id}/{ordre_id}/{livraison_id}
    defaults: { _controller: "APMVenteBundle:Trade:transfererOffre" }
