apm_transport_livraison:
    resource: "@APMTransportBundle/Resources/config/routing/livraison.yml"
    prefix:   /transport/livraison

apm_transport_homepage:
    path:     /transport
    defaults: { _controller: APMTransportBundle:Default:index }

apm_transport_livreur_boutique:
    resource: "@APMTransportBundle/Resources/config/routing/livreur_boutique.yml"
    prefix:   /transport/livreur_boutique

apm_transport_transporteur:
    resource: "@APMTransportBundle/Resources/config/routing/profile_transporteur.yml"
    prefix:   /transport/transporteur

apm_transport_zone_intervention:
    resource: "@APMTransportBundle/Resources/config/routing/zone_intervention.yml"
    prefix:   /transport/zone_intervention

apm_transport_Transporteur_zoneIntervention:
    resource: "@APMTransportBundle/Resources/config/routing/transporteur_zone.yml"
    prefix:   /transport-zone_intervention