apm_transport_livraison:
    resource: "@APMTransportBundle/Resources/config/routing/livraison.yml"
    prefix:   /transport_livraison

apm_transport_homepage:
    path:     /transport
    defaults: { _controller: APMTransportBundle:Default:index }

apm_transport_livreur_boutique:
    resource: "@APMTransportBundle/Resources/config/routing/livreur_boutique.yml"
    prefix:   /transport_livreur_boutique

apm_transport_transporteur:
    resource: "@APMTransportBundle/Resources/config/routing/profile_transporteur.yml"
    prefix:   /transport_transporteur

apm_transport_zone_intervention:
    resource: "@APMTransportBundle/Resources/config/routing/zone_intervention.yml"
    prefix:   /transport_zone_intervention