apm_transport_livraison:
    type: rest
    resource: APM\TransportBundle\Controller\LivraisonController
    name_prefix: api_transport_

apm_transport_livreur_boutique:
    type: rest
    resource: APM\TransportBundle\Controller\Livreur_boutiqueController
    name_prefix: api_transport_


apm_transport_transporteur:
    type: rest
    resource: APM\TransportBundle\Controller\Profile_transporteurController
    name_prefix: api_transport_

apm_transport_zone_intervention:
    type: rest
    resource: APM\TransportBundle\Controller\Zone_interventionController
    name_prefix: api_transport_

apm_transport_transporteur_zoneIntervention:
    type: rest
    resource: APM\TransportBundle\Controller\Transporteur_zoneInterventionController
    name_prefix: api_transport_
