apm_animation_base_documentaire_index:
    path:     /
    defaults: { _controller: "APMAnimationBundle:Base_documentaire:index" }
    methods:  GET

apm_animation_base_documentaire_show:
    path:     /{id}/show
    defaults: { _controller: "APMAnimationBundle:Base_documentaire:show" }
    methods:  GET

apm_animation_base_documentaire_new:
    path:     /new
    defaults: { _controller: "APMAnimationBundle:Base_documentaire:new" }
    methods:  [GET, POST]

apm_animation_base_documentaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMAnimationBundle:Base_documentaire:edit" }
    methods:  [GET, POST]

apm_animation_base_documentaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMAnimationBundle:Base_documentaire:delete" }
    methods:  DELETE

apm_animation_base_documentaire_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMAnimationBundle:Base_documentaire:deleteFromList" }

apm_animation_base_documentaire_download:
    path:     /{id}/download
    defaults: { _controller: "APMAnimationBundle:Base_documentaire:downloadFile" }
    methods:  GET