<?php

namespace APM\TransportBundle\Repository;

/**
 * Livreur_boutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Livreur_boutiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
