<?php

namespace APM\TransportBundle\Repository;

/**
 * TranspoteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class TransporteurRepository extends \Doctrine\ORM\EntityRepository
{
}
