<?php

namespace APM\TransportBundle\Repository;

/**
 * Zone_interventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Zone_interventionRepository extends \Doctrine\ORM\EntityRepository
{
}
