apm_transport_livreur_boutique_index:
    path:     /
    defaults: { _controller: "APMTransportBundle:Livreur_boutique:index" }
    methods:  GET

apm_transport_livreur_boutique_show:
    path:     /{id}/show
    defaults: { _controller: "APMTransportBundle:Livreur_boutique:show" }
    methods:  GET

apm_transport_livreur_boutique_new:
    path:     /new
    defaults: { _controller: "APMTransportBundle:Livreur_boutique:new" }
    methods:  [GET, POST]

apm_transport_livreur_boutique_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMTransportBundle:Livreur_boutique:edit" }
    methods:  [GET, POST]

apm_transport_livreur_boutique_delete:
    path:     /{id}/delete/
    defaults: { _controller: "APMTransportBundle:Livreur_boutique:delete" }
    methods:  DELETE

apm_transport_livreur_boutique_deleteFromList:
    path:     /list/{id}/delete/
    defaults: { _controller: "APMTransportBundle:Livreur_boutique:deleteFromList" }


