apm_zone_intervention_index:
    path:     /
    defaults: { _controller: "APMTransportBundle:Zone_intervention:index" }
    methods:  GET

apm_zone_intervention_show:
    path:     /{id}/show
    defaults: { _controller: "APMTransportBundle:Zone_intervention:show" }
    methods:  GET

apm_zone_intervention_new:
    path:     /new
    defaults: { _controller: "APMTransportBundle:Zone_intervention:new" }
    methods:  [GET, POST]

apm_zone_intervention_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMTransportBundle:Zone_intervention:edit" }
    methods:  [GET, POST]

apm_zone_intervention_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMTransportBundle:Zone_intervention:delete" }
    methods:  DELETE

apm_zone_intervention_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMTransportBundle:Zone_intervention:deleteFromList" }

