<?php

namespace APM\AnimationBundle\Repository;

/**
 * base_documentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Base_documentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
