apm_user_communication_index:
    path:     /
    defaults: { _controller: "APMUserBundle:Communication:index" }
    methods:  GET

apm_user_communication_show:
    path:     /{id}/show
    defaults: { _controller: "APMUserBundle:Communication:show" }
    methods:  GET

apm_user_communication_new:
    path:     /new
    defaults: { _controller: "APMUserBundle:Communication:new" }
    methods:  [GET, POST]

apm_user_communication_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMUserBundle:Communication:edit" }
    methods:  [GET, POST]

apm_user_communication_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMUserBundle:Communication:delete" }
    methods:  DELETE

apm_user_communication_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMUserBundle:Communication:deleteFromList" }
