apm_user_commentaire_index:
    path:     /
    defaults: { _controller: "APMUserBundle:Commentaire:index" }
    methods:  GET

apm_user_commentaire_show:
    path:     /{id}/show
    defaults: { _controller: "APMUserBundle:Commentaire:show" }
    methods:  GET

apm_user_commentaire_new:
    path:     /new
    defaults: { _controller: "APMUserBundle:Commentaire:new" }
    methods:  [GET, POST]

apm_user_commentaire_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMUserBundle:Commentaire:edit" }
    methods:  [GET, POST]

apm_user_commentaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMUserBundle:Commentaire:delete" }
    methods:  DELETE

apm_user_commentaire_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMUserBundle:Commentaire:deleteFromList" }

