apm_user_individu-to-groupe_index:
    path:     /
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:index" }
    methods:  GET

apm_user_individu-to-groupe_show:
    path:     /{id}/show
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:show" }
    methods:  GET

apm_user_individu-to-groupe_new:
    path:     /new
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:new" }
    methods:  [GET, POST]

apm_user_individu-to-groupe_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:edit" }
    methods:  [GET, POST]

apm_user_individu-to-groupe_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:delete" }
    methods:  DELETE

apm_user_individu-to-groupe_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:deleteFromList" }
