apm_user_individu-to-groupe_index:
    path:     /
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:index" }
    methods:  GET

apm_user_groupe_individu_index:
    path:     /group/{id}
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:index" }
    methods:  GET

apm_user_individu_to_groupe_liste-user_index:
    path:     /liste/utilisateurs-groupe/{id}
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:listUsers" }
    methods:  GET

apm_user_individu_to_conversational-group_index:
    path:     /conversational-group
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:indexConversationalGroup" }
    methods:  GET

apm_user_individu-to-groupe_show:
    path:     /{id}/show
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:show" }
    methods:  GET

apm_user_individu-to-groupe_new:
    path:     /new
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:new" }
    methods:  [GET, POST]

apm_user_groupe_individu_new:
    path:     /new/groupe/{id}
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:new" }
    methods:  [GET, POST]

apm_user_individu-to-groupe_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:edit" }
    methods:  [GET, POST]

apm_user_individu-to-groupe_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:delete" }
    methods:  DELETE

apm_user_individu-to-groupe_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMUserBundle:Individu_to_groupe:deleteFromList" }
