apm_user_message_index:
    path:     /
    defaults: { _controller: "APMUserBundle:Message:index" }
    methods:  GET

apm_user_message_show:
    path:     /{id}/show
    defaults: { _controller: "APMUserBundle:Message:show" }
    methods:  GET

apm_user_message_new:
    path:     /new
    defaults: { _controller: "APMUserBundle:Message:new" }
    methods:  [GET, POST]

apm_user_message_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMUserBundle:Message:edit" }
    methods:  [GET, POST]

apm_user_message_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMUserBundle:Message:delete" }
    methods:  DELETE

apm_user_message_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMUserBundle:Message:deleteFromList" }
