apm_user_piece-jointe_index:
    path:     /
    defaults: { _controller: "APMUserBundle:Piece_jointe:index" }
    methods:  GET

apm_user_piece-jointe_show:
    path:     /{id}/show
    defaults: { _controller: "APMUserBundle:Piece_jointe:show" }
    methods:  GET

apm_user_piece-jointe_new:
    path:     /new
    defaults: { _controller: "APMUserBundle:Piece_jointe:new" }
    methods:  [GET, POST]

apm_user_piece-jointe_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMUserBundle:Piece_jointe:edit" }
    methods:  [GET, POST]

apm_user_piece-jointe_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMUserBundle:Piece_jointe:delete" }
    methods:  DELETE

apm_user_piece-jointe_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMUserBundle:Piece_jointe:deleteFromList" }

