<?php

namespace APM\AchatBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Service_apres_venteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Service_apres_venteRepository extends EntityRepository
{
    public function getSavAvecClients()
    {
        $qb = $this->createQueryBuilder('sav')
            ->leftJoin('sav.client', 'c')
            ->addSelect('c');

        return $qb->getQuery()->getResult();
    }

    public function getSavAvecOffres()
    {
        $qb = $this->createQueryBuilder('sav')
            ->leftJoin('sav.offres', 'o')
            ->addSelect('o');

        return $qb->getQuery()->getResult();
    }


}
