apm_user_profile_edit:
    path:     /edit #masque fos_user.profile_edit
    defaults: { _controller: APMUserBundle:ProfileUtilisateurAVM:edit }
    methods: [GET, POST]

apm_admin_profile_edit:
    path:     /edit-admin
    defaults: { _controller: APMUserBundle:ProfileAdmin:edit }
    methods: [GET, POST]

apm_user_profile_show-image:
    path:     /user-image
    defaults: { _controller: APMUserBundle:Profile:showImage }
    methods: [GET, POST]

