apm_achat_groupe_index:
    path:     /
    defaults: { _controller: "APMAchatBundle:Groupe_offre:index" }
    methods:  [GET, POST]

apm_achat_groupe_offres_index:
    path:     /{id}/offres
    defaults: { _controller: "APMAchatBundle:Groupe_offre:listeOffresGroupe" }
    methods:  GET

apm_achat_groupe_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMAchatBundle:Groupe_offre:index" }
    methods:  [GET, POST]

apm_achat_groupe_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMAchatBundle:Groupe_offre:delete" }