apm_achat_service_apres_vente_index:
    path:     /index
    defaults: { _controller: "APMAchatBundle:Service_apres_vente:index" }

apm_achat_service_apres_vente_loader:
    path:     /ajax-table_1
    defaults: { _controller: "APMAchatBundle:Service_apres_vente:loadTable" }

apm_achat_service_apres_vente_loader2:
    path:     /ajax-table_2
    defaults: { _controller: "APMAchatBundle:Service_apres_vente:loadTable" }

apm_achat_service_apres_vente_delete:
    path:     /delete
    defaults: { _controller: "APMAchatBundle:Service_apres_vente:delete" }