apm_achat_service_apres_vente_index:
    path:     /
    defaults: { _controller: "APMAchatBundle:Service_apres_vente:index" }
    methods:  [GET, POST]

apm_achat_service_apres_vente_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMAchatBundle:Service_apres_vente:delete" }