apm_core_super-admin_role-edit:
    path:     /role/
    defaults: { _controller: "APMAdminBundle:Staff/UserRole:grantRole" }
    methods:  [GET, POST]

apm_core_super-admin_role-show:
    path:     /show/{id}
    defaults: { _controller: "APMAdminBundle:Staff/UserRole:grantRoleShow" }
    methods:  GET