apm_marketing_commissionnement_index:
    path:     /
    defaults: { _controller: "APMMarketingDistribueBundle:Commissionnement:index" }
    methods:  GET

apm_marketing_commissionnement_boutique_index:
    path:     /boutique/{id}
    defaults: { _controller: "APMMarketingDistribueBundle:Commissionnement:index" }
    methods:  GET


apm_marketing_commissionnement_conseiller-boutique_index:
    path:     /conseiller-boutique/{id}
    defaults: { _controller: "APMMarketingDistribueBundle:Commissionnement:index" }
    methods:  GET

apm_marketing_commissionnement_show:
    path:     /{id}/show
    defaults: { _controller: "APMMarketingDistribueBundle:Commissionnement:show" }
    methods:  GET

apm_marketing_commissionnement_new:
    path:     /new/{id}
    defaults: { _controller: "APMMarketingDistribueBundle:Commissionnement:new" }
    methods:  [GET, POST]

apm_marketing_commissionnement_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMMarketingDistribueBundle:Commissionnement:edit" }
    methods:  [GET, POST]

apm_marketing_commissionnement_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMMarketingDistribueBundle:Commissionnement:delete" }
    methods:  DELETE
apm_marketing_commissionnement_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMMarketingDistribueBundle:Commissionnement:deleteFromList" }


