apm_marketing_conseiller_boutique_index:
    path:     /{id}/liste-boutiques
    defaults: { _controller: "APMMarketingDistribueBundle:Conseiller_boutique:index" }
    methods:  GET

apm_marketing_conseiller_boutique_index-boutique:
    path:     /{id}/liste-conseillers
    defaults: { _controller: "APMMarketingDistribueBundle:Conseiller_boutique:indexListeConseillerBoutique" }
    methods:  GET

apm_marketing_conseiller_boutique_show:
    path:     /{id}/show
    defaults: { _controller: "APMMarketingDistribueBundle:Conseiller_boutique:show" }
    methods:  GET

apm_marketing_conseiller_boutique_new:
    path:     /new
    defaults: { _controller: "APMMarketingDistribueBundle:Conseiller_boutique:new" }
    methods:  [GET, POST]

apm_marketing_conseiller_boutique_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMMarketingDistribueBundle:Conseiller_boutique:edit" }
    methods:  [GET, POST]

apm_marketing_conseiller_boutique_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMMarketingDistribueBundle:Conseiller_boutique:delete" }
    methods:  DELETE

apm_marketing_conseiller_boutique_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMMarketingDistribueBundle:Conseiller_boutique:deleteFromList" }



