apm_marketing_quota_index:
    path:     /{id}
    defaults: { _controller: "APMMarketingDistribueBundle:Quota:index" }
    methods:  GET

apm_marketing_quota_show:
    path:     /{id}/show
    defaults: { _controller: "APMMarketingDistribueBundle:Quota:show" }
    methods:  GET

apm_marketing_quota_new:
    path:     /new
    defaults: { _controller: "APMMarketingDistribueBundle:Quota:new" }
    methods:  [GET, POST]

apm_marketing_quota_edit:
    path:     /{id}/edit
    defaults: { _controller: "APMMarketingDistribueBundle:Quota:edit" }
    methods:  [GET, POST]

apm_marketing_quota_delete:
    path:     /{id}/delete
    defaults: { _controller: "APMMarketingDistribueBundle:Quota:delete" }
    methods:  DELETE

apm_marketing_quota_deleteFromList:
    path:     /list/{id}/delete
    defaults: { _controller: "APMMarketingDistribueBundle:Quota:deleteFromList" }

