evm_produit_all:
    path:     /
    defaults: { _controller: APMCoreBundle:Platform/Produit:index }
evm_produit_all_get:
    path:     /all
    defaults: { _controller: APMCoreBundle:Platform/Produit:getAll }
evm_produit_check_out:
    path:     /check_out
    defaults: { _controller: APMCoreBundle:Platform/Produit:check }
evm_produit_compare:
    path:     /compare
    defaults: { _controller: APMCoreBundle:Platform/Produit:compare }