apm_staff_admin:
    type: rest
    resource: APM\AdminBundle\Controller\AdminController
    name_prefix: api_admin_

apm_staff_gestionnaire:
    type: rest
    resource: APM\AdminBundle\Controller\GestionController
    name_prefix: api_admin_
