<?php

namespace APM\UserBundle\Repository;

/**
 * Groupe_relationnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Groupe_relationnelRepository extends \Doctrine\ORM\EntityRepository
{
}
