<?php

namespace APM\UserBundle\Repository;

/**
 * Individu_to_groupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Individu_to_groupeRepository extends \Doctrine\ORM\EntityRepository
{
}
