<?php

namespace APM\UserBundle\Repository;

/**
 * Piece_jointeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Piece_jointeRepository extends \Doctrine\ORM\EntityRepository
{
}
