<?php

namespace APM\VenteBundle\Repository;

/**
 * BoutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoutiqueRepository extends \Doctrine\ORM\EntityRepository
{
    /*Pour former une collection d'offres
    * rechercher tous les offre dans la b ayant pour boutique donnée et affecter a la collection avant de transmettre à la vue
    */

}
