<?php

namespace APM\VenteBundle\Repository;

/**
 * Rabais_offreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rabais_offreRepository extends \Doctrine\ORM\EntityRepository
{
}
