<?php

namespace APM\VenteBundle\Repository;

/**
 * RemiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemiseRepository extends \Doctrine\ORM\EntityRepository
{
}
