<?php

namespace APM\VenteBundle\Repository;

/**
 * Suggestion_produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Suggestion_produitRepository extends \Doctrine\ORM\EntityRepository
{
}
