<?php

namespace APM\VenteBundle\Repository;

/**
 * Transaction_produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Transaction_produitRepository extends \Doctrine\ORM\EntityRepository
{
}
