<?php

namespace APM\MarketingDistribueBundle\Repository;

/**
 * CommissionnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionnementRepository extends \Doctrine\ORM\EntityRepository
{
}
