<?php

namespace APM\MarketingDistribueBundle\Repository;

/**
 * ConseillerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConseillerRepository extends \Doctrine\ORM\EntityRepository
{
}
