<?php

namespace APM\MarketingDistribueBundle\Repository;

/**
 * Conseiller_boutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Conseiller_boutiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
