<?php

namespace APM\MarketingDistribueBundle\Repository;

/**
 * QuotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotaRepository extends \Doctrine\ORM\EntityRepository
{
}
