APM\UserBundle\Entity\Utilisateur_avm
    exclusion_policy: ALL
    properties:
        code:
            expose: true
        username:
            expose: true
        email:
            expose: true