apm_user_communication:
    type: rest
    resource: APM\UserBundle\Controller\CommunicationController
    name_prefix: api_user_

apm_user_commentaire:
    type: rest
    resource: APM\UserBundle\Controller\CommentaireController
    name_prefix: api_user_

apm_user_groupe-relationnel:
    type: rest
    resource: APM\UserBundle\Controller\Groupe_relationnelController
    name_prefix: api_user_

apm_user_individu-to-groupe:
    type: rest
    resource: APM\UserBundle\Controller\Individu_to_groupeController
    name_prefix: api_user_

#---------- FOS/APM security--------

apm_user_profile:
    type:  rest
    resource: APM\UserBundle\Controller\ProfileUtilisateurAVMController
    name_prefix: api_user_

apm_user_change_password:
    type:  rest
    resource: APM\UserBundle\Controller\ChangePasswordController
    name_prefix: api_user_
