apm_user_homepage:
    path:     /user
    defaults: { _controller: APMUserBundle:Default:index }
    
apm_admin_registration:
    path:  /register-admin
    defaults: { _controller: APMUserBundle:RegistrationAdmin:register }


#Gestion des ressources utilisateurs
apm_user_communication:
    resource: "@APMUserBundle/Resources/config/routing/communication.yml"
    prefix:   /user_communication

apm_user_commentaire:
    resource: "@APMUserBundle/Resources/config/routing/commentaire.yml"
    prefix:   /user_commentaire

apm_user_groupe-relationnel:
    resource: "@APMUserBundle/Resources/config/routing/groupe_relationnel.yml"
    prefix:   /user_groupe-relationnel

apm_user_individu-to-groupe:
    resource: "@APMUserBundle/Resources/config/routing/individu_to_groupe.yml"
    prefix:   /user_individu-to-groupe

apm_user_piece-jointe:
    resource: "@APMUserBundle/Resources/config/routing/piece_jointe.yml"
    prefix:   /user_piece-jointe