apm_user_homepage:
    path:     /user
    defaults: { _controller: APMUserBundle:Default:index }
    
apm_admin_registration:
    path:  /register-staff
    defaults: { _controller: APMUserBundle:RegistrationAdmin:register }

#Gestion des ressources utilisateurs
apm_user_communication:
    resource: "@APMUserBundle/Resources/config/routing/communication.yml"
    prefix:   /user/communication

apm_user_commentaire:
    resource: "@APMUserBundle/Resources/config/routing/commentaire.yml"
    prefix:   /user/commentaire

apm_user_groupe-relationnel:
    resource: "@APMUserBundle/Resources/config/routing/groupe_relationnel.yml"
    prefix:   /user/groupe-relationnel

apm_user_individu-to-groupe:
    resource: "@APMUserBundle/Resources/config/routing/individu_to_groupe.yml"
    prefix:   /user/individu-to-groupe

apm_user_profile:
    resource: "@APMUserBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /user/system