apm_marketing_reseau_homepage:
    path:     /marketing_reseau
    defaults: { _controller: APMMarketingReseauBundle:Default:index }

apm_marketing_reseau:
    resource: "@APMMarketingReseauBundle/Resources/config/routing/reseau_conseillers.yml"
    prefix:   /marketing/reseau
